nodeLinker: node-modules

packageExtensions:
  "@turbo/gen@*":
    peerDependencies:
      typescript: "*"
      "@types/node": "*"
    peerDependenciesMeta:
      typescript:
        optional: true
      "@types/node":
        optional: true
  "@typescript-eslint/utils@*":
    peerDependencies:
      typescript: "*"
    peerDependenciesMeta:
      typescript:
        optional: true
  "@turbo/workspaces@*":
    peerDependencies:
      "@types/node": "*"
    peerDependenciesMeta:
      "@types/node":
        optional: true
  "inquirer@8.2.7":
    peerDependencies:
      "@types/node": "*"
    peerDependenciesMeta:
      "@types/node":
        optional: true
