name: CI

on:
  pull_request:
  push:
    branches: [main, dev, atik]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          # Do not use built-in yarn cache here; it queries yarn before Corepack activation
      - name: Enable Corepack
        run: corepack enable
      - name: Activate Yarn Berry (4.9.2)
        run: corepack prepare yarn@4.9.2 --activate
      - name: Show Yarn version
        run: yarn --version
      - name: Cache Yarn (Berry) artifacts
        uses: actions/cache@v4
        with:
          path: |
            .yarn/cache
            .yarn/unplugged
            .yarn/build-state.yml
            .yarn/install-state.gz
            .pnp.cjs
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        run: yarn install --immutable
      - name: Generate Prisma Client (incl. TypedSQL)
        run: yarn db:generate
        env:
          DATABASE_URL: postgresql://user:pass@localhost:5432/scholar_flow
          DIRECT_DATABASE_URL: postgresql://user:pass@localhost:5432/scholar_flow
      - name: Type Check
        run: yarn type-check
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
